# -*- coding: utf-8 -*-
# ------------  LandlordApproval --------------
# 房东审批
Approval:
  # 房东初审
  landlord_first_approval_btn: ['xpath','//*[@id="app"]/div/div/div/div[2]/div/div[2]/div/div/div/div[1]/div[3]/div/div[1]/div/table/tbody/tr[1]/td[17]/div/div']
  # 房东审批弹框 alert 确定按钮
  landlord_first_approval_confirm_btn : ['xpath','/html/body/div[4]/div/div/div[2]/div/div[2]/button[2]']
  # 房东复审
  landlord_Review_approval_btn: ['xpath','//*[@id="app"]/div/div/div/div[2]/div/div[2]/div/div/div/div[1]/div[3]/div/div[1]/div/table/tbody/tr[1]/td[19]/div/div/div']
  # 房东复审弹框 alert 确定按钮
  landlord_Review_approval_confirm_btn : ['xpath','/html/body/div[6]/div/div/div[2]/div/div[2]/button[2]']

  # 点击更多按钮(登记房东审批)
  more_btn: ['xpath','//*[@id="app"]/div/div/div/div[2]/div/div[1]/div/div/div/div/form/div[5]/button[2]']
  # 点击审批状态
  approval_status_selection: ['xpath','//*[@id="app"]/div/div/div/div[2]/div/div[1]/div/div/div/div/form/div[6]/div[2]/div/div/div/div/div/input']
  # 选择审批状态
  approval_status_dropdown: ['xpath','/html/body/div[2]/div[5]/div/div/div[1]/ul/li[1]']
  # 点击搜索按钮
  search_btn: ['xpath','//*[@id="app"]/div/div/div/div[2]/div/div[1]/div/div/div/div/form/div[5]/button[1]']