# -*- coding: utf-8 -*-
# ------------  LoginPage --------------
LoginPage:
  # 账号
  username_input: ['xpath','/html/body/div/div/div/div[1]/form/div[3]/input']
  # 密码
  pwd_input: ['xpath','/html/body/div/div/div/div[1]/form/div[4]/div/input']
  # 登录按钮
  login_btn: ['xpath','/html/body/div/div/div/div[1]/form/div[6]/div/button']