# -*- coding: utf-8 -*-
# ------------  RegisterLandLord --------------
#登记房东按钮
RegisterLandLord:
  # 登记房东按钮
  register_landlord_btn: ['xpath','//*[@id="app"]/div/div[1]/div[2]/button[1]']
  # 下一步按钮 (房东信息)
  click_landlord_next_btn: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[3]/button[2]']
  # 下一步按钮 (物品信息)
  click_item_next_btn: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[3]/div[3]/button[2]/span']
  # 下一步按钮 (预览账单)
  click_bill_next_btn: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[4]/div[3]/button[2]/span']
  # 提交初审按钮
  submit_first_review_btn: [ 'xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[5]/div[3]/button[2]/span' ]
  # 提交复审按钮
  submit_second_review_btn: [ 'xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[5]/div[3]/button[3]/span' ]
# ------------  LandlordBaseInfo --------------
LandlordBaseInfo:
  # 点击店面
  element_shop_selection: ['xpath','/html/body/div[1]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[2]/div[1]/div/div/div/div/div/input']
  # 点击店面下拉菜单
  element_shop_dropdown: ['xpath','/html/body/div[2]/div[1]/div[1]/ul/li[1]']
  # 输入房屋楼幢
  building_number_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[2]/div[3]/div/div/div/div[1]/input']
  # 输入房屋单元
  unit_number_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[2]/div[3]/div/div/div/div[2]/input']
  # 输入门牌号
  house_number_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[2]/div[4]/div/div/div/div/input']
  # 点击物业地址
  element_property_address_selection: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[2]/div[7]/div/div/div/div/div[1]/input']
  # 点击物业地址下拉菜单
  element_property_address_dropdown: ['xpath','/html/body/div[3]/div[1]/div[1]/ul/li[1]']
  # 输入建筑面积
  building_area_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[2]/div[8]/div/div/div/div[1]/div/input']
  # 点击房屋类型
  element_house_type_selection: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[2]/div[9]/div/div/div/div[1]/input']
  # 点击房屋类型下拉菜单
  element_house_type_dropdown: ['xpath','/html/body/div[4]/div[1]/div[1]/ul/li[1]']
  # 点击装修程度
  element_decoration_level_selection: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[2]/div[10]/div/div/div/div/div[1]/input']
  # 点击装修程度下拉菜单
  element_decoration_level_dropdown: ['xpath','/html/body/div[5]/div[1]/div[1]/ul/li[1]']
  # 输入所在楼层
  floor_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[2]/div[11]/div/div/div/div[1]/input']
  # 输入总楼层
  all_floor_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[2]/div[11]/div/div/div/div[2]/input']
  # 点击朝向
  element_orientation_selection: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[2]/div[12]/div/div/div/div/div[1]/input']
  # 点击朝向下拉菜单
  element_orientation_dropdown: ['xpath','/html/body/div[6]/div[1]/div[1]/ul/li[1]']

# ------------  LandlordInfo --------------
# 房东信息
LandlordInfo:
  # 输入房东姓名
  landlord_name_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[4]/div[1]/div/div/div/div/input']
  # 输入证件号码
  id_number_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[4]/div[2]/div/div[2]/input']
  # 输入手机号码
  iphone_number_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[4]/div[3]/div/div/div/div/input']
  # 输入收款人姓名
  payee_name_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[4]/div[4]/div/div/div/div/input']
  # 输入银行卡卡号
  bank_cards_number_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[4]/div[6]/div/div/div/div/input']
  # 输入身份证号码
  payee_id_number_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[4]/div[7]/div/div/div/div/input']
  # 输入收款人手机号
  payee_phone_number_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[4]/div[8]/div/div/div/div/input']
  # 点击渠道来源
  element_channel_source_selection: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[4]/div[9]/div/div/div/div/div[1]/input']
  # 点击渠道来源下拉菜单
  element_channel_source_dropdown: ['xpath','/html/body/div[7]/div[1]/div[1]/ul/li[1]']
  # 点击房东包物业
  element_landlord_Property_selection: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[4]/div[10]/div/div/div/div[1]/div/input']
  # 点击房东包物业下拉菜单
  element_landlord_Property_dropdown: ['xpath','/html/body/div[8]/div[1]/div[1]/ul/li[2]/span']

# ------------  TrusteeshipInfo --------------
# 托管信息
TrusteeshipInfo:
  # 点击合同期限 3年
  joint_deadline_btn: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[6]/div[3]/div/div/div/span[1]']
  # 输入收房价格
  house_price_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[6]/div[5]/div/div/div/input']
  # 点击房屋押金 押一
  house_deposit_btn: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[6]/div[6]/div/div/div/span']
  # 点击维修方案
  element_repair_scheme_selection: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[6]/div[7]/div/div/div/div/div[1]/input']
  # 点击维修方案下拉菜单
  element_repair_scheme_dropdown: ['xpath','/html/body/div[9]/div[1]/div[1]/ul/li[1]']
  # 点击装修方案
  element_renovation_plan_selection: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[6]/div[8]/div/div/div/div/div[1]/div[1]/input']
  # 点击装修方案下拉菜单
  element_renovation_plan_dropdown: ['xpath','/html/body/div[10]/div[1]/div[1]/ul/li[1]']
  # 点击首次付款日期选择
  element_payment_date_selection: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[6]/div[9]/div/div/div/div/input']
  # 点击首次付款日期下拉菜单
  element_payment_date_dropdown: ['xpath','/html/body/div[11]/div[1]/div/div[2]/table[1]/tbody/tr[6]/td[5]']
  # 点击业务人员
  element_business_people_selection: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[6]/div[10]/div/div/div/div/div[1]/input']
  # 点击业务人员下拉菜单
  element_business_people_dropdown: ['xpath','/html/body/div[12]/div[1]/div[1]/ul/li[1]']
  # 点击累计免租期
  element_cumulation_Rent-free_period_selection: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[6]/div[12]/div/div/div/div/div/div[1]/div/div[1]/input']
  # 点击累计免租期下拉菜单
  element_cumulation_Rent-free_period_dropdown: ['xpath','/html/body/div[13]/div[1]/div[1]/ul/li[1]/span']
  # 输入备注
  remark_textarea: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[16]/div/div/div/div/div/div/textarea']
# -------------  registerItems --------------
# 物品信息
itemInformation:
  # 点击物品名称
  element_item_name_selection: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[3]/div[2]/div[2]/div[3]/table/tbody/tr/td[2]/div/div/div[1]/input']
  # 点击物品名称下拉菜单
  element_item_name_dropdown: ['xpath','/html/body/div[14]/div[1]/div[1]/ul/li[1]/span']
  # 输入物品数量
  item_number_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[3]/div[2]/div[2]/div[3]/table/tbody/tr/td[3]/div/div/input']
  # 输入物品备注
  item_remark_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[3]/div[2]/div[2]/div[3]/table/tbody/tr/td[5]/div/div/input']
  # 点击物品图片
  item_image_btn: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[3]/div[2]/div[2]/div[3]/table/tbody/tr/td[6]/div/span[1]']
  # 上传物品图片
  item_image_input: ['xpath','/html/body/div[14]/div/div[2]/div/div[1]/div/div/div[1]/div/i']
  # 删除物品按钮
  item_delete_btn: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[3]/div[2]/div[2]/div[3]/table/tbody/tr/td[7]/div/i']

# ------------  uploadContractInfo --------------
# 上传合同
uploadContractInfo:
  # 上传房产证照片
  title_deeds_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[5]/div[2]/div[2]/div[1]/div/div[1]/div/input']
  # 上传身份证照片
  identity_card_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[5]/div[2]/div[2]/div[2]/div/div[1]/div/input']
  # 上传委托书照片
  entrustment_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[5]/div[2]/div[2]/div[3]/div/div[1]/div/input']
  # 原房照片
  original_house_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[5]/div[2]/div[2]/div[4]/div/div[1]/div/input']
  # 合同上传
  contract_upload_input: ['xpath','//*[@id="app"]/div/div[2]/div[2]/div/div[5]/div[2]/div[2]/div[5]/div/div[1]/div/input']
