# -*- coding: utf-8 -*-
# ------------  RegisterTenant --------------

# 租客租赁状态下拉选择
rentalStatusSearch:
    # 租赁状态下拉
    element_rental_status_selection_js: 'document.querySelector("#app > div > div:nth-child(2) > div > div:nth-child(1) > div > div.el-card__header > div > div > div > form > div:nth-child(2) > div > div > div > input").click()'
    # 未租状态下拉选择
    element_rental_status_dropdown_js: 'document.querySelector("body > div.el-select-dropdown.el-popper > div.el-scrollbar > div.el-select-dropdown__wrap.el-scrollbar__wrap > ul > li:nth-child(1)").click()'
    # 搜索
    whole_tenement_search_btn_js: 'document.querySelector("#app > div > div:nth-child(2) > div > div:nth-child(1) > div > div.el-card__header > div > div > div > form > div:nth-child(5) > button.el-button.el-button--danger.el-button--mini").click()'
# 登记租客按钮
registerTenant:
    # 登记租客按钮
    register_tenant_btn_js: 'document.querySelector("#app > div > div:nth-child(2) > div > div:nth-child(1) > section > main > div.el-card.table-container.is-never-shadow > div > div > div > div.el-table__fixed-right > div.el-table__fixed-body-wrapper > table > tbody > tr:nth-child(1) > td.el-table_1_column_24.is-center.el-table__cell > div > div:nth-child(1) > button").click()'
    # 租客信息页面下一步按钮
    tenant_information_next_button: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[3]/button[2]']
    # 预览账单页面下一步按钮
    tenant_bill_next_button: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[3]/div[5]/button[2]']
    # 发起审批按钮 初审
    tenant_approval_button: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[3]/div[3]/button[2]']
# 租客信息填写
    # 租客姓名
    tenant_name_input: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[4]/div[1]/div/div/div/div[1]/input']
    # 证件类型下拉
    element_identity_type_selection: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[4]/div[2]/div/div[1]/div/input']
    # 证件类型选择
    element_identity_type_dropdown: ['xpath','/html/body/div[2]/div[1]/div[1]/ul/li[3]']
    # 证件号码
    tenant_id_input : ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[4]/div[2]/div/div[2]/input']
    # 联系人电话
    contact_person_phone_input: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[4]/div[3]/div/div/div/div[1]/input']
    # 紧急联系人电话
    emergency_phone_input: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[4]/div[4]/div/div/div/div/input']
    # 业务人员下拉
    element_business_person_selection: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[4]/div[5]/div/div/div/div/div[1]/input']
    # 业务人员选择
    element_business_person_dropdown: ['xpath','/html/body/div[2]/div[1]/div[1]/ul/li[3]']
    # 协助人员下拉
    element_help_person_selection: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[5]/div[2]/div/div/div/div/input']
    # 协助人员选择
    element_help_person_dropdown: ['xpath','/html/body/div[4]/div[1]/div[1]/ul/li[1]']
    # 渠道来源下拉
    element_channel_source_selection: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[5]/div[4]/div/div/div/div/div[1]/input']
    # 渠道来源选择
    element_channel_source_dropdown: ['xpath','/html/body/div[5]/div[1]/div[1]/ul/li[1]']

# 租赁信息填写
    # 租赁期限下拉 年
    element_rental_period_years_selection: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[7]/div[3]/div/div/div/div[1]/div/div[1]/input']
    # 租赁期限选择 年
    element_rental_period_years_dropdown: ['xpath','/html/body/div[6]/div[1]/div[1]/ul/li[3]']
    # 租赁期限下拉 月
    element_rental_period_month_selection: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[7]/div[3]/div/div/div/div[2]/div/div/input']
    # 租赁期限选择 月
    element_rental_period_month_dropdown: ['xpath','/html/body/div[7]/div[1]/div[1]/ul/li[5]']
    # 缴费方式
    payment_method_btn: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[8]/div[1]/div/div/div/div[2]/div/span']
    # 出房价格
    out_room_price_input: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[8]/div[2]/div/div/div/div[1]/div/input']
    # 房屋押金
    house_deposit_btn: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[8]/div[3]/div/div/div/div[2]/div/span']
    # 提前缴费
    pre_payment_btn: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[8]/div[4]/div/div/div/div[2]/div/span[1]']

# 其它扣费 + 备注
    # 定金抵扣
    deposit_deduction_input: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[11]/div[1]/div/div/div/div/input']
    # 优惠抵扣
    discount_deduction_input: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[11]/div[2]/div/div/div/div/input']
    # 备注
    remark_textarea: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[2]/div[2]/form/div[17]/div/div/div/div/div/textarea']

# 上传合同
    # 身份证照片
    identity_card_input: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[3]/div[2]/div[2]/div/div/div/div/div[1]/div/input']
    # 合同上传
    contract_upload_input: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[3]/div[2]/div[4]/div/div/div/div/div[1]/div/input']
    # 交割单照片
    delivery_photo_input: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[3]/div[2]/div[6]/div/div/div/div/div[1]/div/input']
    # 其他
    other_input: ['xpath','//*[@id="app"]/div/div[2]/div/div[1]/div/div[3]/div[2]/div[8]/div/div/div/div/div[1]/div/input']